-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 16:17:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blog` DEFAULT CHARACTER SET utf8 ;
USE `Blog` ;

-- -----------------------------------------------------
-- Table `Blog`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(70) NULL,
  `Content` LONGTEXT NULL,
  `Court` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Articles_has_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Articles_has_Categories` (
  `Articles_id` INT NOT NULL,
  `Categories_id` INT NOT NULL,
  PRIMARY KEY (`Articles_id`, `Categories_id`),
  CONSTRAINT `fk_Articles_has_Categories_Articles`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `Blog`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Categories_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `Blog`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Mots-clefs` VARCHAR(70) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Articles_Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Articles_Tags` (
  `Articles_id` INT NOT NULL,
  `Tags_id` INT NOT NULL,
  PRIMARY KEY (`Articles_id`, `Tags_id`),
  CONSTRAINT `fk_Articles_has_Tags_Articles1`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `Blog`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Tags_Tags1`
    FOREIGN KEY (`Tags_id`)
    REFERENCES `Blog`.`Tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Commentaires` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(70) NULL,
  `site` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NULL,
  `Content` MEDIUMTEXT NULL,
  `Articles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Commentaires_Articles1`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `Blog`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(70) NULL,
  `pass` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
